# Generated by Django 5.1.6 on 2025-02-17 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='created_by',
            new_name='posted_by',
        ),
    ]
